### ISSUE TITLE
Support für Shelly Plug S

### ISSUE THREAD

**Issue by jojunker** [solectrus/shelly-collector#193]
Hallo @ledermann,

ich habe mich in den letzten Tagen mit dem Shelly Connector beschäftigt um mit der aktuellen Solectrus Beta einzelne kleinere Verbraucher darzustellen. Das funktioniert prima mit meinen neueren Shelly Plug Plus aber leider nicht mit meinen älteren Plugs.

Im Docker Logfile sehe ich diese Information:

```

2024-12-18 12:30:51 Shelly collector for SOLECTRUS, Version 0.4.1, built at 2024-11-09T06:34:29.008Z
2024-12-18 12:30:51 https://github.com/solectrus/shelly-collector
2024-12-18 12:30:51 Copyright (c) 2024 Georg Ledermann, released under the MIT License
2024-12-18 12:30:51 
2024-12-18 12:30:51 Using Ruby 3.3.6 on platform x86_64-linux-musl
2024-12-18 12:30:51 Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement dryer
2024-12-18 12:30:51 Pulling from your Shelly (Gen1) at http://10.31.22.36/status every 5 seconds
2024-12-18 12:30:51 
2024-12-18 12:30:51 Got record #1 at 2024-12-18 12:30:54 +0100 within 30 ms, Power 0.0 W
2024-12-18 12:30:51 Successfully pushed record #1 to InfluxDB
2024-12-18 12:30:56 
2024-12-18 12:30:56 Got record #2 at 2024-12-18 12:30:59 +0100 within 28 ms, Power 0.0 W
2024-12-18 12:30:56 Successfully pushed record #2 to InfluxDB
2024-12-18 12:31:02 
2024-12-18 12:31:02 Got record #3 at 2024-12-18 12:31:04 +0100 within 241 ms, Power 0.0 W
2024-12-18 12:31:02 Successfully pushed record #3 to InfluxDB

```
die IP Adresse ist richtig und es scheint "irgendwas" zurück zu kommen und wird als 0 interpretiert
Der Output ip/status sieht zur gleichen Zeit so aus:

```

{
    "wifi_sta": {
        "connected": true,
        "ssid": "xxxx",
        "ip": "10.31.22.36",
        "rssi": -86
    },
    "cloud": {
        "enabled": true,
        "connected": true
    },
    "mqtt": {
        "connected": false
    },
    "time": "12:31",
    "unixtime": 1734521482,
    "serial": 3,
    "has_update": false,
    "mac": "80646F838326",
    "cfg_changed_cnt": 0,
    "actions_stats": {
        "skipped": 0
    },
    "relays": [
        {
            "ison": true,
            "has_timer": false,
            "timer_started": 0,
            "timer_duration": 0,
            "timer_remaining": 0,
            "overpower": false,
            "source": "input"
        }
    ],
    "meters": [
        {
            "power": 99.28,
            "overpower": 0,
            "is_valid": true,
            "timestamp": 1734525082,
            "counters": [
                40.336,
                0,
                0
            ],
            "total": 40
        }
    ],
    "temperature": 31.32,
    "overtemperature": false,
    "tmp": {
        "tC": 31.32,
        "tF": 88.38,
        "is_valid": true
    },
    "update": {
        "status": "idle",
        "has_update": false,
        "new_version": "20230913-113421/v1.14.0-gcb84623",
        "old_version": "20230913-113421/v1.14.0-gcb84623",
        "beta_version": "20231107-164219/v1.14.1-rc1-g0617c15"
    },
    "ram_total": 52056,
    "ram_free": 38896,
    "fs_size": 233681,
    "fs_free": 166413,
    "uptime": 139
}

```

Kannst Du mit den Informationen etwas anfangen?
Kann gerne weitere Tests durchführen.
Danke

**Comment by ledermann** [comment]
Was genau ist das für ein Shelly? Mich wundert, dass die Werte in `meters` stehen, implementiert habe ich `emeters`, also mit einem `e` davor.

Kannst du hier genaueres herausfinden?
https://shelly-api-docs.shelly.cloud/gen1/#shelly-family-overview

**Comment by megaholti** [comment]
Habe das gleiche Problem mit dem Plug S 2. Der Plug ist der einzige Plug mit einer Maximallast von 3500w. Der wird aktuell in der Gen 2 verkauft. Softwareseitig ist dies wohl "Gen1". Die Daten werden hier aufrufbar über status Webseite auf im Wert "power" und nicht "epower", somit kann der Collector diese nicht auslesen und meldet 0W. Auch das Webportal unterscheidet sich grundlegend von den Plug S: 
![Uploading Bildschirmfoto 2024-12-18 um 14.41.47.png…]()

<img width="2048" alt="Bildschirmfoto 2024-12-18 um 14 09 02" src="https://github.com/user-attachments/assets/fa72f1fe-144b-42f6-ae35-198aecb3cf79" />

**Comment by jojunker** [comment]
Link zu dem Shelly:
https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs

Das ist der erste kleine Shelly Plug, der ausgliefert wurde.
Modell: SHPLG-S

In den Infos zu den Plugs steht unter diesem Link zum /status :
https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs-status

![image](https://github.com/user-attachments/assets/608e0732-0b77-46a0-9549-aa1f013f149b)

und
![image](https://github.com/user-attachments/assets/110712fa-a6df-43c9-9c14-ceabbd403580)

Meine neueren Shelly PlusPlugS habe ich mit GEN=2 eingebunden - die geben die Power richtig zurück

**Comment by megaholti** [comment]
> Link zu dem Shelly: https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs
> 
> Das ist der erste kleine Shelly Plug, der ausgliefert wurde. Modell: SHPLG-S
> 
> In den Infos zu den Plugs steht unter diesem Link zum /status : https://shelly-api-docs.shelly.cloud/gen1/#shelly-plug-plugs-status
> 
> ![image](https://private-user-images.githubusercontent.com/88735738/396940066-608e0732-0b77-46a0-9549-aa1f013f149b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Mjk4NTgsIm5iZiI6MTczNDUyOTU1OCwicGF0aCI6Ii84ODczNTczOC8zOTY5NDAwNjYtNjA4ZTA3MzItMGI3Ny00NmEwLTk1NDktYWExZjAxM2YxNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEzNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1M2QzYjc1NDkwMzY0ZDZjMDhjN2NlNTExMmI3OTE0Yzk1MGEyNTY5MWNkMmI0ZmQ2MTVkOTBiMzA5MTdlNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pp8cqJPn8I0oYCLXjy88cQ55ZM8_T1eu1J4hG1dmqWk)
> 
> und ![image](https://private-user-images.githubusercontent.com/88735738/396941005-110712fa-a6df-43c9-9c14-ceabbd403580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Mjk4NTgsIm5iZiI6MTczNDUyOTU1OCwicGF0aCI6Ii84ODczNTczOC8zOTY5NDEwMDUtMTEwNzEyZmEtYTZkZi00M2M5LTljMTQtY2VhYmJkNDAzNTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEzNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTY5MDI3MjgyODE5YWU2NzM4MmEyMDc5OTIyM2RjZWMxNWE5NjFjNDFmYjMyZTgwY2Q5ZmRhODE4NzVmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wTvOmFu_EeNEZ0Wu-akuB_N2A4gtYftEpt9_c7D6J4c)
> 
> Meine neueren Shelly PlusPlugS habe ich mit GEN=2 eingebunden - die geben die Power richtig zurück

ja die Kleineren habe ich auch und die laufen auch, aber eben nur mit einer Maximallast von 2500w, das reicht z.B. für Backöfen nicht aus, die brauchen 3500. darum wird der auch noch immer verkauft, hat ein Alleinstellungsmerkmal.

**Comment by megaholti** [comment]
Wenn ich es jetzt richtig verstanden habe, müsste der Collector in soweit angepasst werden, wenn z.b. 1. Gen Plugs benutzt werden, dass die werte in "meters" stehen und nicht wie bei 2. Gen in "emeters" - ich sehe hier sonst keine andere Variante - kann aber gerne testen

**Comment by ledermann** [comment]
Ok, danke für die allseitigen Rückmeldungen :)

Wie es aussieht, gibt es den "Shelly Plug S" sowohl in Gen1 als auch in Gen2. Ich habe den Collector jetzt so angepasst, dass bei Verwendung von `SHELLY_GEN=1` die Werte erst in `emeters` gesucht werden und dann, wenn dort nichts ist, bei `meters`. Somit sollte es jetzt für beide Generationen funktionieren.

Zum Ausprobieren bitte den Shelly-Collector auf `develop` wechseln. Mal sehen, ob es damit bei Euch funktioniert.

**Comment by megaholti** [comment]
läuft :-)
thin 30 ms, Power 4.0 W
solectrus-shelly-collector-oven-1  | Successfully pushed record #4 to InfluxDB

es laufen beide Gen1 und Gen2 - Top danke!

kann wegen mir eigentlich geschlossen werden :-)

**Comment by jojunker** [comment]
Funktioniert!

```
2024-12-18 15:44:55 Shelly collector for SOLECTRUS, Version develop, built at 2024-12-18T14:07:55.774Z
2024-12-18 15:44:55 https://github.com/solectrus/shelly-collector
2024-12-18 15:44:55 Copyright (c) 2024 Georg Ledermann, released under the MIT License
2024-12-18 15:44:55 
2024-12-18 15:44:55 Using Ruby 3.3.6 on platform x86_64-linux-musl
2024-12-18 15:44:55 Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement dryer
2024-12-18 15:44:55 Pulling from your Shelly (Gen1) at http://10.31.22.36/status every 5 seconds
2024-12-18 15:44:55 
2024-12-18 15:44:55 Got record #1 at 2024-12-18 15:44:58 +0100 within 32 ms, Power 99.3 W
2024-12-18 15:44:56 Successfully pushed record #1 to InfluxDB
2024-12-18 15:45:00 
2024-12-18 15:45:00 Got record #2 at 2024-12-18 15:45:03 +0100 within 33 ms, Power 99.3 W
2024-12-18 15:45:00 Successfully pushed record #2 to InfluxDB
```

Danke !!!

**Comment by ledermann** [comment]
Prima, ich habe gerade [v0.5.0](https://github.com/solectrus/shelly-collector/releases/tag/v0.5.0) released, ihr könnt also wieder zurück auf `latest` wechseln.
