### ISSUE TITLE
Shelly collector blieb einfach stehen

### ISSUE THREAD

**Issue by esusxunil** [solectrus/shelly-collector#20]
Guten morgen,

ich hatte mich heute morgen gewundert, dasss keine Daten für die Wärmepumpe vorlagen. Im Portainer habe ich dann gesehen, dass der Container für den Shelly Collector (und nur der) im Status Stopped war. Er lies sich dann direkt wieder starten und die Daten lagen dann auch direkt wieder vor.

Im Log fand sich leider kein Hinweis warum der Collector stehen geblieben ist:

> Successfully pushed record #48830 to InfluxDB
> Got record #48831 at 2024-03-13 17:22:52 +0000 within 35 ms, Power 27.168 W, Temperature 41.5 °C
> Successfully pushed record #48831 to InfluxDB
> Shelly collector for SOLECTRUS, Version 0.1.1, built at 2024-03-02T05:46:25.969Z
> https://github.com/solectrus/shelly-collector
> Copyright (c) 2024 Georg Ledermann, released under the MIT License
> Using Ruby 3.3.0 on platform aarch64-linux-musl
> Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement SENEC
> Pulling from your Shelly at http://192.168.2.201 every 5 seconds
> Got record #1 at 2024-03-14 07:37:11 +0000 within 83 ms, Power 9.522 W, Temperature 41.2 °C
> Successfully pushed record #1 to InfluxDB

Ich beobachte es mal und berichte, ob es nochmal auftritt.

**Comment by ledermann** [comment]
Du könntest in der `docker-compose.yml` prüfen, was beim Shelly-Collector unter `restart` eingestellt ist. Es gibt zwei sinnvolle Möglichkeiten:

- `restart: always`: Der Container wird immer neu gestartet, wenn er stoppt. Das schließt Stopps ein, die durch den Docker-Daemon oder durch den Benutzer veranlasst werden. Das bedeutet, der Container läuft quasi immer, außer er wird explizit entfernt oder Docker selbst wird gestoppt.

- `restart: unless-stopped`: Ähnlich wie `restart: always`, mit dem Unterschied, dass der Container nicht automatisch neu gestartet wird, wenn er vom Benutzer gestoppt wurde (z.B. durch einen Befehl wie `docker stop <container>`). Wenn der Container aus anderen Gründen stoppt oder der Docker-Daemon neu gestartet wird, wird der Container jedoch automatisch neu gestartet.

Ich sehe gerade, dass ich in meiner [kleinen Anleitung](https://github.com/orgs/solectrus/discussions/2861#discussion-6281290) diese Option gar nicht erwähnt hatte. Das ist ungünstig, denn: Wenn man keine `restart`-Option in der Docker-Container-Konfiguration angibt, verwendet Docker standardmäßig die Einstellung `restart: no`. Das bedeutet, dass der Container nicht automatisch neu gestartet wird, wenn er stoppt, der Docker-Daemon neu gestartet wird (z.B. bei Update von Docker oder Reboot) oder der Container aus irgendeinem Grund abstürzt. 

Ich habe in der Anleitung gerade `restart: unless-stopped` ergänzt.

**Comment by esusxunil** [comment]
War der richtige Tipp, habe das docker-compose angepasst und neu ausgefuehrt.

Danke dir.
