### ISSUE TITLE
Fehler "uninitialized constant ShellyAdapter::Error"

### ISSUE THREAD

**Issue by ledermann** [solectrus/shelly-collector#89]
> Die Abfrage des Shellys klappt nicht, das log sagt
>
> ```
> shelly-collector-1    | Error getting data from Shelly at http://10.10.13.16: uninitialized constant ShellyAdapter::Error
>```
>
> Die IP stimmt aber auf jeden Fall. Was mir auffällt: die Abfragt geht als http raus, der Shelly antwortet aber auf https. Der Shelly macht aber ja selbst ne redirection nach https, sodass es hier eigentlich kein Problem geben sollte.
> Muss ich am Shelly selbst noch etwas einstellen?

_Originally posted by @Oggy512 in https://github.com/solectrus/solectrus/issues/3281#issuecomment-2241634480_

**Comment by ledermann** [comment]
@Oggy512: Der Shelly leitet auf `https` weiter? Welcher Shelly ist denn das und wo kann man das einstellen? Wie regelt der Shelly denn das dafür erforderliche Zertifikat?

Derzeitig unterstützt der Shelly-Collector jedenfalls kein `https`. Ich kann das aber gerne ergänzen. Für dich wäre eine schnellere Lösung, wenn du den Shelly auf `http` einstellst, sofern möglich.

Die Fehlermeldung im Log ist natürlich auch doof, da tritt ein Fehler im Fehler auf. Das kläre ich noch.

**Comment by ledermann** [comment]
Ich habe jetzt den "Fehler im Fehler" korrigiert, d.h. bei Verbindungsproblemen wird nun eine sinnvollere Fehlermeldung erscheinen. Das Update auf [v0.3.3](https://github.com/solectrus/shelly-collector/releases/tag/v0.3.3) des Shelly-Collector steht bereit und kann (wie gewohnt) installiert werden mit `docker compose pull && docker compose up -d`.

Nach wie vor wird aber kein `https`-Connect möglich sein. Bevor ich das implementiere, warte ich noch dein Feedback ab.

**Comment by Oggy512** [comment]
Mea culpa!
Hab nur auf die schnelle im Browser geschaut und mich von der Chrome "Verbindung nicht sicher" Meldung irre führen lassen. Der Shelly macht kein https, sondern nur http und deswegen sagt Chrome natürlich nicht sicher.
Nichtsdestotrotz kriege ich nen 404 Fehler im Collector, jetzt mit neuer Version.

```
shelly-collector-1  | Shelly collector for SOLECTRUS, Version 0.3.3, built at 2024-07-21T15:55:17.434Z
shelly-collector-1  | https://github.com/solectrus/shelly-collector
shelly-collector-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
shelly-collector-1  |
shelly-collector-1  | Using Ruby 3.3.4 on platform x86_64-linux-musl
shelly-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket, measurement heatpump
shelly-collector-1  | Pulling from your Shelly at http://10.10.13.16 every 5 seconds
shelly-collector-1  | Error getting data from Shelly at http://10.10.13.16: 404
shelly-collector-1  | Error getting data from Shelly at http://10.10.13.16: 404
```

Es handelt sich um einen Shelly EM3, FW: 20230913-114244/v1.14.0-gcb84623.
Die IP stimmt...

**Comment by ledermann** [comment]
Oha, ein [Shelly 3EM](https://www.shelly.com/de/products/shop/shelly-3em-1), also ohne Pro. Der gehört zu Generation 1 und wird (noch) nicht vom Shelly-Collector unterstützt.

Ich kann das aber ergänzen. Kannst du bitte vorher ausprobieren, ob folgende Abfrage im Browser funktioniert:

http://10.10.13.16/status

Da müsste u.a. die Angabe `total_power` erscheinen. Wenn dem so ist, ergänze ich den Support für Gen1-Geräte (siehe #90).

**Comment by Oggy512** [comment]
Genau, ohne Pro... der Nachteil, wenn man früh mit Smarthome anfängt, irgendwann sind Dinge alt :-D

Die query auf den /status Endpunkt funktioniert und liefert ein JSON zurück, siehe:

``
{"wifi_sta":{"connected":true,"ssid":"xxx","ip":"10.10.13.16","rssi":-53},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"18:51","unixtime":1721580697,"serial":3,"has_update":false,"mac":"3494547B6253","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":true,"source":"input"}],"emeters":[{"power":3.33,"pf":0.51,"current":0.03,"voltage":236.14,"is_valid":true,"total":148019.6,"total_returned":15.3},{"power":0.00,"pf":-0.00,"current":1.75,"voltage":235.59,"is_valid":true,"total":1744539.0,"total_returned":701.9},{"power":66.71,"pf":0.64,"current":0.45,"voltage":234.70,"is_valid":true,"total":1174011.1,"total_returned":0.0}],"total_power":70.04,"emeter_n":{"current":0.00,"ixsum":1.57,"mismatch":false,"is_valid":false},"fs_mounted":true,"v_data":1,"ct_calst":0,"update":{"status":"idle","has_update":false,"new_version":"20230913-114244/v1.14.0-gcb84623","old_version":"20230913-114244/v1.14.0-gcb84623","beta_version":"20231107-165007/v1.14.1-rc1-g0617c15"},"ram_total":49920,"ram_free":31208,"fs_size":233681,"fs_free":154616,"uptime":697}
``

**Comment by ledermann** [comment]
Ok, besten Dank, dann schließe ich das mal hier. Implementierung dann in #90.

Ich weiß aber noch nicht, wann ich dazu komme. Falls du auch MQTT im Haus haben solltest, wäre es möglicherweise schneller, wenn du das verwendest. Also dafür sorgen, dass die Messwerte vom Shelly in einem MQTT-Broker vorliegen, diesen dann mit dem [MQTT-Collector](https://github.com/solectrus/mqtt-collector) abfragen und die Werte so nach SOLECTRUS bringen.
