### ISSUE TITLE
Support für Gen1-Geräte

### ISSUE THREAD

**Issue by ledermann** [solectrus/shelly-collector#90]
Ein [Shelly 3EM](https://www.shelly.com/de/products/shop/shelly-3em-1) wird derzeitig nicht unterstützt. 

API:
https://shelly-api-docs.shelly.cloud/gen1/#shelly-3em-status

Beispiel-Response von `/status`:
```json
{
   "wifi_sta":{
      "connected":true,
      "ssid":"xxx",
      "ip":"10.10.13.16",
      "rssi":-53
   },
   "cloud":{
      "enabled":false,
      "connected":false
   },
   "mqtt":{
      "connected":false
   },
   "time":"18:51",
   "unixtime":1721580697,
   "serial":3,
   "has_update":false,
   "mac":"3494547B6253",
   "cfg_changed_cnt":0,
   "actions_stats":{
      "skipped":0
   },
   "relays":[
      {
         "ison":false,
         "has_timer":false,
         "timer_started":0,
         "timer_duration":0,
         "timer_remaining":0,
         "overpower":false,
         "is_valid":true,
         "source":"input"
      }
   ],
   "emeters":[
      {
         "power":3.33,
         "pf":0.51,
         "current":0.03,
         "voltage":236.14,
         "is_valid":true,
         "total":148019.6,
         "total_returned":15.3
      },
      {
         "power":0.00,
         "pf":-0.00,
         "current":1.75,
         "voltage":235.59,
         "is_valid":true,
         "total":1744539.0,
         "total_returned":701.9
      },
      {
         "power":66.71,
         "pf":0.64,
         "current":0.45,
         "voltage":234.70,
         "is_valid":true,
         "total":1174011.1,
         "total_returned":0.0
      }
   ],
   "total_power":70.04,
   "emeter_n":{
      "current":0.00,
      "ixsum":1.57,
      "mismatch":false,
      "is_valid":false
   },
   "fs_mounted":true,
   "v_data":1,
   "ct_calst":0,
   "update":{
      "status":"idle",
      "has_update":false,
      "new_version":"20230913-114244/v1.14.0-gcb84623",
      "old_version":"20230913-114244/v1.14.0-gcb84623",
      "beta_version":"20231107-165007/v1.14.1-rc1-g0617c15"
   },
   "ram_total":49920,
   "ram_free":31208,
   "fs_size":233681,
   "fs_free":154616,
   "uptime":697
}
```

**Comment by marco221087** [comment]
Please the code for a normal 3em expand.
anscheinend funktioniert er nur für die pro Version!

**Comment by ledermann** [comment]
@marco221087 Der Shelly-Collector unterstützt momentan den *Shelly Pro 3EM* und den *Shelly Plug S*. Es fehlt noch die Unterstützung für Gen1-Geräte - und vermutlich andere Geräte von Shelly.

Kannst du bestätigen, dass dein Shelly 3EM so reagiert wie oben beschrieben, also auf `http://ip-adresse/status` das angegebene JSON liefert? Ich habe selbst keinen 3EM (ohne Pro) und kann das nicht ausprobieren.

**Comment by marco221087** [comment]
Hallo Georg, Hier der Status Text: {"wifi_sta":{"connected":true,"ssid":"FRITZ!Box 7590 YF","ip":"192.168.178.79","rssi":-45},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":true},"time":"19:50","unixtime":1726163405,"serial":15879,"has_update":false,"mac":"485519DAC918","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":true,"source":"input"}],"emeters":[{"power":33.59,"pf":0.12,"current":1.25,"voltage":229.41,"is_valid":true,"total":399476.5,"total_returned":0.0},{"power":5.22,"pf":0.02,"current":0.99,"voltage":230.72,"is_valid":true,"total":310273.8,"total_returned":919.7},{"power":2.66,"pf":0.01,"current":0.98,"voltage":22994,"is_valid":true,"total":224937.6,"total_returned":630.1}],"total_power":41.47,"emeter_n":{"current":0.00,"ixsum":0.35,"mismatch":false,"is_valid":false},"fs_mounted":true,"v_data":1,"ct_calst":0,"update":{"status":"idle","has_update":false,"new_version":"20230913-114244/v1.14.0-gcb84623","old_version":"20230913-114244/v1.14.0-gcb84623","beta_version":"20231107-165007/v1.14.1-rc1-g0617c15"},"ram_total":49920,"ram_free":29956,"fs_size":233681,"fs_free":154365,"uptime":169698}

**Comment by deadrabbit87** [comment]
Ich war mal so frei, und hab Ausgabe lesbarer formatiert: 
```
{
    "wifi_sta": {
        "connected": true,
        "ssid": "FRITZ!Box 7590 YF",
        "ip": "192.168.178.79",
        "rssi": -48
    },
    "cloud": {
        "enabled": false,
        "connected": false
    },
    "mqtt": {
        "connected": true
    },
    "time": "08:22",
    "unixtime": 1726208570,
    "serial": 22647,
    "has_update": false,
    "mac": "485519DAC918",
    "cfg_changed_cnt": 0,
    "actions_stats": {
        "skipped": 0
    },
    "relays": [{
            "ison": false,
            "has_timer": false,
            "timer_started": 0,
            "timer_duration": 0,
            "timer_remaining": 0,
            "overpower": false,
            "is_valid": true,
            "source": "input"
        }
    ],
    "emeters": [{
            "power": 714.94,
            "pf": 0.84,
            "current": 3.64,
            "voltage": 234.69,
            "is_valid": true,
            "total": 399856.1,
            "total_returned": 0.0
        }, {
            "power": 554.36,
            "pf": 0.83,
            "current": 2.83,
            "voltage": 235.38,
            "is_valid": true,
            "total": 310379.3,
            "total_returned": 919.7
        }, {
            "power": 555.62,
            "pf": 0.83,
            "current": 2.84,
            "voltage": 235.05,
            "is_valid": true,
            "total": 225028.1,
            "total_returned": 630.2
        }
    ],
    "total_power": 1824.92,
    "emeter_n": {
        "current": 0.00,
        "ixsum": 1.15,
        "mismatch": false,
        "is_valid": false
    },
    "fs_mounted": true,
    "v_data": 1,
    "ct_calst": 0,
    "update": {
        "status": "idle",
        "has_update": false,
        "new_version": "20230913-114244/v1.14.0-gcb84623",
        "old_version": "20230913-114244/v1.14.0-gcb84623",
        "beta_version": "20231107-165007/v1.14.1-rc1-g0617c15"
    },
    "ram_total": 49920,
    "ram_free": 30284,
    "fs_size": 233681,
    "fs_free": 154365,
    "uptime": 214861
}
```

**Comment by marco221087** [comment]
Hallo, Ja, sorry! Ich hab ihn nur so aus dem Status kopiert, ging mit dem Handy nicht anders… Bekommen Sie eine Anpassung hin oder muss ich mir einen anderen Shelly einbauen?

**Comment by ledermann** [comment]
Alles liegt vor, wird bei Gelegenheit implementiert.

**Comment by marco221087** [comment]
Hallo, Wissen sie schon wann sie dazu kommen den Shelly 3em zu implementieren?  Dieser misst bei mir die Heizung und wollte gern vor der nächsten Heizsession die Anzeige implementieren haben, ansonsten muss ich mir noch ein anderes Messmittel suchen. 
    Mit freundlichen Grüßen Marco Jacobi0162/5109761
  

 Von: Georg Ledermann ***@***.***>Gesendet: Freitag, September 13, 2024 9:24 AMAn: solectrus/shelly-collector ***@***.***>Cc: marco221087 ***@***.***>; Mention ***@***.***>Betreff: Re: [solectrus/shelly-collector] Support für Shelly 3EM (Issue #90) 
Alles liegt vor, wird bei Gelegenheit implementiert.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
Mit freundlichen Grüßen Marco Jacobi0162/5109761

**Comment by ledermann** [comment]
Ok, aufgrund der vielfachen Nachfrage habe ich das nun implementiert :-)
Jetzt benötige ich Feedback, da ich das im "luftleeren" Raum gebaut habe, ohne einen Generation-1-Shelly verfügbar zu haben.

Bitte ausprobieren wie folgt:

1. In der `docker-compose.yml` das **Docker-Tag** wechseln von `latest` auf `develop`, außerdem die neue Variable `SHELLY_GEN` bekanntmachen, es muss also folgendes da stehen:

   ```yaml
     shelly-collector:
       image: ghcr.io/solectrus/shelly-collector:develop
       ...
       environment:
         - SHELLY_GEN
         - ...
   ```

2. Folgende Zeile in der `.env` ergänzen:

    ```
    SHELLY_GEN=1
    ```

    ("Gen" steht für "Generation", Standard ist `2`, d.h. für bestehende Nutzer ändert sich nichts)

Dann neues Docker-Image holen und alles neu starten:

```
docker compose pull 
docker compose up -d
```

Bitte jetzt das Log im Auge behalten:

```
docker compose logs shelly-collector
```

Darin muss das Gen1-Gerät erwähnt sein. Falls das aus ungeklärten Gründen nicht so ist oder sonstige Probleme bestehen, bitte mir **unbedingt** den Ausschnitt aus dem Log schicken.

Ein korrekter Output für Gen1-Geräte sollte so aussehen:

```
Shelly collector for SOLECTRUS, Version develop, built at 2024-09-26T09:47:07.325Z
https://github.com/solectrus/shelly-collector
Copyright (c) 2024 Georg Ledermann, released under the MIT License
Using Ruby 3.3.5 on platform x86_64-linux-musl
Pushing to InfluxDB at http://raspi, bucket XXX, measurement YYY
Pulling from your Shelly (Gen1) at http://192.168.123.45/status every 5 seconds
Got record #1 at 2024-09-26 11:54:01 +0200 within 31 ms, Power 0.6 W
Successfully pushed record #1 to InfluxDB

**Comment by deadrabbit87** [comment]
Herzlichen Dank!

LGTM: 
```
solectrus-shelly-collector-1  | Shelly collector for SOLECTRUS, Version develop, built at 2024-09-26T09:47:07.325Z
solectrus-shelly-collector-1  | https://github.com/solectrus/shelly-collector
solectrus-shelly-collector-1  | Copyright (c) 2024 Georg Ledermann, released under the MIT License
solectrus-shelly-collector-1  |
solectrus-shelly-collector-1  | Using Ruby 3.3.5 on platform x86_64-linux-musl
solectrus-shelly-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement my-pv-measurement
solectrus-shelly-collector-1  | Pulling from your Shelly (Gen1) at http://192.168.178.79/status every 5 seconds
solectrus-shelly-collector-1  |
solectrus-shelly-collector-1  | Got record #1 at 2024-09-27 07:10:06 +0000 within 95 ms, Power 37.2 W,
solectrus-shelly-collector-1  | Successfully pushed record #1 to InfluxDB
solectrus-shelly-collector-1  |
solectrus-shelly-collector-1  | Got record #2 at 2024-09-27 07:10:11 +0000 within 217 ms, Power 37.06 W,
solectrus-shelly-collector-1  | Successfully pushed record #2 to InfluxDB
```

**Comment by ledermann** [comment]
@deadrabbit87 Prima, danke für die Rückmeldung. 
Wenn es bei @marco221087 auch funktioniert, stelle ich ein neues Release bereit.

**Comment by deadrabbit87** [comment]
Bitte, das ist von @marco221087. 

Er kann das nur nicht selbst einrichten. 
Bei mir kann ich das nicht testen, da meine WP an einem Shelly EM hängt. 

Der hätte aber folgenden JSON String: 
```
{
    "wifi_sta": {
        "connected": true,
        "ssid": "XXXXXXXXXXXXXXXXXX",
        "ip": "XXXXXXXXXXXXXXXXXX",
        "rssi": -37
    },
    "cloud": {
        "enabled": false,
        "connected": false
    },
    "mqtt": {
        "connected": true
    },
    "time": "09:39",
    "unixtime": 1727422761,
    "serial": 21128,
    "has_update": false,
    "mac": "XXXXXXXXXXXXXXXXXX",
    "cfg_changed_cnt": 0,
    "actions_stats": {
        "skipped": 0
    },
    "relays": [{
            "ison": false,
            "has_timer": false,
            "timer_started": 0,
            "timer_duration": 0,
            "timer_remaining": 0,
            "overpower": false,
            "is_valid": true,
            "source": "input"
        }
    ],
    "emeters": [{
            "power": 3.63,
            "reactive": 0.00,
            "pf": 0.00,
            "voltage": 226.02,
            "is_valid": true,
            "total": 1724256.1,
            "total_returned": 785.7
        }, {
            "power": 6.45,
            "reactive": -13.82,
            "pf": -0.42,
            "voltage": 226.02,
            "is_valid": true,
            "total": 510346.8,
            "total_returned": 194.1
        }
    ],
    "update": {
        "status": "idle",
        "has_update": false,
        "new_version": "20230913-114150/v1.14.0-gcb84623",
        "old_version": "20230913-114150/v1.14.0-gcb84623",
        "beta_version": "20231107-164916/v1.14.1-rc1-g0617c15"
    },
    "ram_total": 51064,
    "ram_free": 34936,
    "fs_size": 233681,
    "fs_free": 150349,
    "uptime": 5071906
}

```
Wäre im Prinzip identisch, nur das der dritte Kanale bzw Phase fehlt.

**Comment by ledermann** [comment]
Jetzt komme ich aber durcheinander - sind @marco221087 und @deadrabbit87 die gleiche Person? ;-)

Und um welche Geräte geht es jetzt genau? Der [jetzt](https://github.com/solectrus/shelly-collector/issues/90#issuecomment-2378621646) beschriebene JSON-Output ist mir vorher nicht begegnet. Das Array `emeters` enthält nur zwei Einträge (statt drei), und die Gesamtsumme `total_power` fehlt ganz. Im ersten Beitrag von @marco221087 so das noch anders aus.

Ich kann das ergänzen, aber es wäre gut, wenn ich genau wüsste, um welche Geräte es sich beim jeweiligen Output handelt.

**Comment by deadrabbit87** [comment]
Ja so ist es. Sorry für die Verwirrung. 

Ich habe das @marco221087 eingerichtet. 

Der JSON Output ist von einem [Shelly EM](https://www.shelly.com/de/products/shop/shelly-em-1x-120a). Der kann nur an der gleichen Phase mit zwei Messwandlerspulen messen. 

Da meine WP aber nur einphasig angeschlossen ist, brauche ich keinen 3EM um der EM reicht bei mir aus.

**Comment by ledermann** [comment]
Ok, ich habe jetzt ergänzt, dass bei Gen1-Geräten der Gesamtverbrauch aus `Phase A + Phase B + Phase C` errechnet wird, falls nicht vom Gerät geliefert (fehlende Phasen werden als 0 gewertet).

Damit werden meiner Ansicht nach nun insgesamt drei zusätzliche Gen1-Geräte unterstützt:

- Shelly EM
- Shelly 3EM
- Shelly Plug S

Aktualisiertes `develop`-Image steht bereit. Wer es ausprobiert hat, bitte angeben, mit welchem Gerät es funktioniert (oder nicht funktioniert).

**Comment by deadrabbit87** [comment]
Herzlichen Dank dafür. Auch beim meinem Shelly EM sieht das gut aus: 
```
Got record #5937 at 2024-09-29 10:40:10 +0200 within 35 ms, Power 8.9 W
Successfully pushed record #5937 to InfluxDB

Got record #5938 at 2024-09-29 10:40:21 +0200 within 133 ms, Power 8.4 W
Successfully pushed record #5938 to InfluxDB

Got record #5939 at 2024-09-29 10:40:31 +0200 within 39 ms, Power 8.870000000000001 W
Successfully pushed record #5939 to InfluxDB

Got record #5940 at 2024-09-29 10:40:41 +0200 within 36 ms, Power 6.59 W
Successfully pushed record #5940 to InfluxDB

Got record #5941 at 2024-09-29 10:40:51 +0200 within 35 ms, Power 7.130000000000001 W
Successfully pushed record #5941 to InfluxDB

Got record #5942 at 2024-09-29 10:41:02 +0200 within 37 ms, Power 8.73 W
Successfully pushed record #5942 to InfluxDB
```
Mir fällt hier nur auf, dass bei manchen Messwerten die Nachkommastellen abweichen: 
```
Got record #5941 at 2024-09-29 10:40:51 +0200 within 35 ms, Power 7.130000000000001 W
Successfully pushed record #5941 to InfluxDB
```

Was aber dringend irgendwo erwähnt werden sollte, ist dass die Werte summiert werden. 

Ich denke, in meinem Fall ist der Shelly EM ein "speziell" angeschlossen. 

Wie schon erwähnt, kann der EM nur an einer Phase zweimal Ströme messen. 

Ich hab hier die eine Messwandlerspule am Innenmodul der Heizung und am Außenmodul die zweite. 

Innen- und Außenmodul hängen aber auf der gleichen Phase. 

Vorstellbar ist aber, dass jemand mit der ersten die Wärmepumpe misst und mit der zweiten irgendwas anderes...

Ich hoffe, es ist verständlich wie ich das meine.

**Comment by ledermann** [comment]
@deadrabbit87 Ok, prima. Die Ausgabe von "Power" erfolgt jetzt gerundet, damit es einheitlich aussieht. Das betrifft aber nur die Log-Ausgabe, für die Datenbank wird der Originalwert durchgereicht. `develop` ist aktualisiert.

Bezüglich der Phasen läuft es so:

- Wenn der Shelly die Phasen A/B/C einzeln liefert, werden diese auch nach InfluxDB geschrieben. Je nachdem, welchen Shelly man hat, liefert die API unterschiedliches zurück. Es wird geschrieben, was da ist (nach `power_a`, `power_b` und `power_c`). 
- Wenn der Shelly den Gesamtverbrauch liefert, wird dieser geschrieben (nach `power`). Fehlt er, wird er (vom Shelly-Collector) berechnet als Summe aus A/B/C. 

Ich habe das [im README ergänzt](https://github.com/solectrus/shelly-collector?tab=readme-ov-file#output).

Wenn du direkt in InfluxDB rein guckst (http://ip:8086), dann siehst du genau, was in deinem Fall geschrieben wurde. Im Log steht der Einfachheit halber nur die Summe.

Wenn also jemand mit einem Shelly zwei oder drei unterschiedliche Geräte misst (eines mit jeder Phase), dann stehen die Werte auch **einzeln** in der Datenbank und können genutzt werden. Die Summe steht dann zwar auch da, wird aber eher nicht benötigt.

Insofern denke ich, ist jetzt alles korrekt so.

**Comment by ledermann** [comment]
Habe jetzt [v0.4.0](https://github.com/solectrus/shelly-collector/releases/tag/v0.4.0) veröffentlicht. Ihr könnt also wieder zurück auf `latest` wechseln.
